#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word 'bash'
for pid in /proc/*/cmdline; do
    process_cmd=$(tr -d '\0' < "$pid")
    if [[ "$process_cmd" == *"bash"* ]]; then
        current_pid=$(echo "$pid" | awk -F'/' '{print $3}')
        process_name=$(tr -d '\0' < "/proc/$current_pid/comm")
        echo "PID: $current_pid, Process Name: $process_name"
    fi
done
