#!/usr/bin/env bash
# This script displays username, user id, and home directory path for users from /etc/passwd
while IFS=':' read -r username _ userid _ _ homedir _
do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
done < /etc/passwd
