#!/usr/bin/env bash
# This script generates a fictional story based on the content of /etc/passwd
while IFS=':' read -r username _ userid groupid info homedir shell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo "USER ID $userid's place is protected by the passcode $info, more info about the user here: $info"
    echo
done < /etc/passwd
