#!/usr/bin/env bash
# Bash script to group visitors by IP and HTTP status code, displaying the occurrence count
log_file="apache-access.log"
awk '{print $1, $9}' "$log_file" | sort | uniq -c | awk '{print $1, $2, $3}' | sort -nr
