#!/usr/bin/env bash
# This script displays "Best School" 10 times, showing "Hi" after the 9th iteration using a while loop and if statement
x=1
while [ $x -le 10 ]
do
    if [ $x -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((x++))
done
