#!/usr/bin/env bash
# This script displays different messages based on the loop iteration using a while loop and if-elif-else statements
x=1
while [ $x -le 10 ]
do
    if [ $x -eq 4 ]
    then
        echo "bad luck"
    elif [ $x -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((x++))
done
