#!/usr/bin/env bash
# This script displays different numbers and associated messages based on specific loop iterations using a while loop and case statement
x=1
while [ $x -le 20 ]
do
    case $x in
        4)
            echo "$x"
            echo "bad luck from China"
            ;;
        9)
            echo "$x"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$x"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$x"
            ;;
    esac
    ((x++))
done
