#!/usr/bin/env bash
# This script displays the content of the current directory in a list format with only the part of the name after the first dash
for file in *
do
    if [[ ! $file == .* && -f $file ]]; then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done
