#!/usr/bin/env bash
# Check if running on Docker
if grep -q docker /proc/1/cgroup;
then
    echo "Running on Docker"
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
else
    echo "Not running on Docker. Script meant for Docker environment."
fi
